---
apiVersion: batch/v1
kind: Job
metadata:
  name: project-
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      name: project-
      labels:
        WorkerType: fargate
        Environment: tests
    spec:
      containers:
      - name: project-
        env:
          - name: K6_INFLUXDB_ORGANIZATION
            value: primary
          - name: K6_INFLUXDB_BUCKET
            value: primary
          - name: K6_INFLUXDB_TOKEN
            value: 8BMAPLyl9CJGc8jTM2lB
        image: registry/image:tag
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
      restartPolicy: Never
