---
apiVersion: batch/v1
kind: Job
metadata:
  name: project-a
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      name: project-a
    spec:
      containers:
      - name: project-a
        image: registry/image:tag
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
      restartPolicy: Never
