---
apiVersion: batch/v1
kind: Job
metadata:
  name: project-
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      name: project-
      labels:
        WorkerType: fargate
        Environment: tests
    spec:
      containers:
      - name: project-
        image: registry/image:tag
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
      restartPolicy: Never
