---
apiVersion: batch/v1
kind: Job
metadata:
  name: project-a
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      name: project-a
    spec:
      containers:
      - name: project-a
        image: norgefajardo/test-k6:37b263732b5946ed14c2ab17b804daa37863ff8e
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
      restartPolicy: Never
