apiVersion:  apdexone.com/v1alpha1
kind: XTest
metadata:
  name: project-estopa
  labels:
    provider: k6
spec:
  id: project-estopa
  compositionRef:
    name: test-k6
  parameters:
    image: "norgefajardo/test-k6:latest"
    schedule: "15 8 * * *"
    cpu: 100m
    memory: 28M
    pods: 2
    duration: 360
    namespace: production
