version: 2.1

executors:
  dind-executor:
    docker:
      - image: cimg/base:2022.03
    working_directory: /tmp/k6-image/

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  docker: circleci/docker@2.1.1


workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          executor: dind-executor



            #assume-web-identity: true
            #aws-cli-version: latest
            #aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
            #aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
            #context: myContext
            #create-repo: true
            #extra-build-args: '--compress'
            #no-output-timeout: 20m
            #platform: linux/amd64
            #public-registry: false
            #push-image: true
            #region: us-east-1
            #registry-id: AWS_ECR_REGISTRY_ID
            #repo-scan-on-push: true
            #skip-when-tags-exist: false
            #source-profile: sourceProfileName
