version: 2

jobs:
  build-image:
    docker:
      - image: docker:dind
        auth:
          username: norgefajardo
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command:  |
            docker build -t test-k6 .
      - deploy:
          name: Push docker image to registry
          command: |
            docker tag test-k6 "norgefajardo/test-k6:${CIRCLE_SHA1}"
            echo $DOCKERHUB_PASSWORD | docker login -u norgefajardo --password-stdin
            docker push "norgefajardo/test-k6:${CIRCLE_SHA1}"
  modify-chart:
    environment:
      schedule: "0 14 * * *"
      replicas: 3
      repository: "eueueueue"
    docker:
      - image: norgefajardo/alpine-git:0.1
    steps:
      - run:
          name: Clone chart repository
          command: |
            git clone https://github.com/stdevNorge/cron-chart.git ~/cron-chart
            envsubst < ~/cron-chart/values.yaml
            cd ~/cron-chart
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
            git add .
            git commit -am "eoouo"
            git push

workflows:
  version: 2
  performance_tests:
    jobs:
      - build-image
      - modify-chart:
          requires:
            - build-image

