version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.1
  kubernetes: circleci/kubernetes@1.3.0

jobs:
  create-job:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - kubernetes/create-or-update-resource:
          resource-file-path: job-template.yaml
          show-kubectl-command: true

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          aws-cli-version: latest
          extra-build-args: '--compress'
          no-output-timeout: 20m
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: us-east-1
          registry-id: AWS_ECR_REGISTRY_ID
          skip-when-tags-exist: false
      - create-job:
          requires:
            - aws-ecr/build-and-push-image
