version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          assume-web-identity: true
          aws-cli-version: latest
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: myContext
          create-repo: true
          executor: aws-ecr/default
          extra-build-args: '--compress'
          no-output-timeout: 20m
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: us-east-1
          registry-id: AWS_ECR_REGISTRY_ID
          repo: myECRRepository
          repo-scan-on-push: true
          skip-when-tags-exist: false
          source-profile: sourceProfileName
          tag: 'latest,myECRRepoTag'
